spring: 
  profiles:
    active: 
      - dev
---
server:
  port: 10002
spring:
  profiles: dev
  application:
    name: cloud-greenwich-config-client-10002
  text: test-bus
---
server:
  port: 10002
spring:
  profiles: test
  application:
    name: cloud-greenwich-config-client-10002
  text: testt-bus
