spring: 
  profiles:
    active: 
      - dev
      
---
spring:
  profiles: dev
  application: 
       name: microservicecloud-config-atwzh-dev
       
---
spring:
  profiles: test
  application: 
     name: microservicecloud-config-atwzh-test
