---
spring:
  profiles: dev
  application:
    name: cloud-greenwich-config-client-10003
  text: test-bus
---
spring:
  profiles: test
  application:
    name: cloud-greenwich-config-client-10003
  text: test
