spring: 
  profiles:
    active: 
      - dev
---
server:
  port: 10003
spring:
  profiles: dev
  application:
    name: 10002-dev
---
server:
  port: 10003
spring:
  profiles: test
  application:
    name: 10002-test
